server:
  port: 9999
security:
  basic:
    enabled: false
spring:
  redis:
    host: localhost
    port: 6379
    password: cISePhIrChOrMACkeTICiAhECludeWha
  application:
    name: omnie-commerce-gateway
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  output:
    ansi:
      enabled: always
  http:
    multipart:
      max-file-size: 4MB
      max-request-size: 5MB
      enabled: true

zuul:
  add-proxy-headers: true
  add-host-header: true
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 50
    max-total-connections: 200
    socket-timeout-millis: 30000
  retryable: true
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 100
  ratelimit:
    key-prefix: omnie-rate-limiter
    enabled: true
    repository: REDIS
    behind-proxy: true
    default-policy: #deprecated - please use "default-policy-list"
      limit: 300 #optional - request number limit per refresh interval window
      quota: 30 #optional - request time limit per refresh interval window (in seconds)
      refresh-interval: 10 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url


logging:
  level:
    root: info
    com.omniesoft: info
    org.springframework.cloud: info
    org.springframework: info
    org.springframework.security: warn

server.error.whitelabel.enabled: false
spring.mvc.throw-exception-if-no-handler-found: true

hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 3
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 61000

ribbon:
  eureka:
    enabled: true
  serverListRefreshInterval: 1000
  maxAutoRetries: 5
  maxAutoRetriesNextServer: 5
  ServerListRefreshInterval: 1000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  connectTimeout: 100
  readTimeout: 60000
  ConnectTimeout: 100
  ReadTimeout: 60000
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 600
  client:
    serviceUrl:
      defaultZone: http://${service.discovery.client.user}:${service.discovery.client.password}@${service.discovery.host}:9998/eureka/

# Custom
service:
  discovery:
    host: localhost
    client:
      user: eureka-client
      password: EuReKaPasSs

---
###
### Profile: dev
###
spring:
  profiles: dev
  redis:
    host: redis
    port: 6379

logging:
  config: classpath:logger-to-file.xml

service:
  discovery:
    host: omnie-discovery
    client:
      user: eureka-client
      password: EuReKaPasSs
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    securePortEnabled: false
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true

---
###
### Profile: prod
###
spring:
  profiles: prod
  redis:
    host: redis
    port: 6379

logging:
  config: classpath:logger-to-file.xml

service:
  discovery:
    host: omnie-discovery
    client:
      user: eureka-client
      password: EuReKaPasSs
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    securePortEnabled: false
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true




